<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>net.wasdev.maven.tools.parents</groupId>
    <version>25.0.0.6-test</version>
    <artifactId>targets-parent</artifactId>
  </parent>
  
  <version>25.0.0.6-test</version>
  <groupId>net.wasdev.maven.tools.targets</groupId>
  <artifactId>liberty-target</artifactId>
  <packaging>pom</packaging>

  <name>Full WebSphere Liberty libraries</name>
  <description>POM targeting WebSphere Liberty APIs, SPIs, Java specifications and third-party libraries.</description>
  <name>WebSphere Liberty dependencies parent POM</name>
  <description>Parent POM for building all WebSphere Liberty dependency POMs</description>
  <url>https://www.ibm.com/</url>
  <licenses>
    <license>
      <name>IBM International License Agreement for Non-Warranted Programs</name>
      <url>https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/maven/licenses/L-JTHS-8SZMHX/HTML/</url>
      <distribution>repo</distribution>
      <comments>Additional notices https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/maven/licenses/L-JTHS-8SZMHX/HTML/notices.html </comments>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/OpenLiberty/open-liberty.git</url>
    <connection>scm:git: https://github.com/OpenLiberty/open-liberty.git</connection>
    <developerConnection>private</developerConnection>
  </scm>
  <developers>
    <developer>
      <id>contbld</id>
      <name>contbld</name>
      <email>contbld@uk.ibm.com</email>
      <organization>IBM</organization>
      <organizationUrl>https://www.ibm.com</organizationUrl>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>liberty-spis</artifactId>
      <version>${project.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>liberty-apis</artifactId>
      <version>${project.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>java-specs</artifactId>
      <version>${jspecs.libs.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>third-party</artifactId>
      <version>${thirdparty.libs.version}</version>
      <type>pom</type>
    </dependency>
  </dependencies>
</project>
